<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DeadLetter.fs" />
    <Compile Include="Store.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShipmentTracker.Domain\ShipmentTracker.Domain.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.6" />
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
  </ItemGroup>

</Project>

